### ISSUE TITLE
Can we use model ensemble (mean teacher) instead of s temporal ensemble

### ISSUE THREAD

**Issue by luyvlei** [shengliu66/ELR#11]
I want to use elr in larger dataset, but temporal ensemble is high memory cost. Has anybody tried that before?

**Comment by shengliu66** [comment]
Interesting, how did you generate the noise in this task? My suggestion would be that check whether early learning actually happens or not. ELR would work if "early-learning" really happens.

**Comment by shengliu66** [comment]
Indeed, you need ground truth labels to check.
