### ISSUE TITLE
the result of clothing 1m 

### ISSUE THREAD

**Issue by lisenbuaa** [shengliu66/ELR#19]
hi authors,
      I run your open code with clothing 1m dataset. I did not modify your configs. But the best accuracy in clothing 1m is 74.37 and i run many times. I cannot reset the 74.81 reported in your paper. would you please help me complete the reproduction of 74.81 accuracy. maybe, you can tell me the best hyperparameters.
      Good luck!
      Best wishes for you!

**Comment by shengliu66** [comment]
Could you check whether ur configuration is the same as what has been described in the paper?
