### ISSUE TITLE
good job, but...

### ISSUE THREAD

**Issue by wangzhenzhou2020** [shengliu66/ELR#22]
too heavy... It's hard to understanding the project. You really don't need so much inheritance to implement your method. Just as [Co-Teaching](https://github.com/bhanML/Co-teaching)  is enough. And it's not easy to find if you  get the performance through your method or some unknown tricks.

**Comment by shengliu66** [comment]
Thanks for your suggestion, all we propose is a loss function which we have already put in the readme file, and all the technical details are described in the paper.
