### ISSUE TITLE
i want to know how to use the test.py

### ISSUE THREAD

**Issue by qiuxiaolong857** [shengliu66/ELR#26]
After l train the model,i want to start test in ELR plus,but when the code in 'checkpoint = torch.load(config.resume,map_location='cpu')',the bug said it invalid load key, '{'  so the test could't read the resume file? how to solve it? the resume path 'dir/to/model/models/cifar10_ELR_plus_PreActResNet18_sym_80/0721_205920/config.json'

**Comment by shengliu66** [comment]
You need to specify the directory to the model correctly.
