### ISSUE TITLE
Negative total loss

### ISSUE THREAD

**Issue by LeeDoYup** [shengliu66/ELR#5]
Hello, Thx for the awesome project !
When I reproduce the loss in my own project,
I has found that the total loss is below the zero, because of the regularization term.
(The total loss can go to negative infinite.)

Is it right?

**Comment by shengliu66** [comment]
Hi, the total loss can be negative, and but usually, it won't go to negative infinity as it means the value of the inner product equals 1 which is difficult to achieve.
