### ISSUE TITLE
Code for reproducing Figure 1 of your paper

### ISSUE THREAD

**Issue by mohitsharma29** [shengliu66/ELR#7]
Hey

I was wondering whether you will release the code you used to perform the experiments demonstrated in figure 1. I was hoping to recreate those for different architectures and much more. 

Thanks

**Comment by shengliu66** [comment]
Hey, thanks for your attention to the work, we don't have a script but a jupyter notebook for that, so we will not going to release the code. But reproducing the figure should not be hard, you can send me emails if you meet any issues, I'm happy to help.
